name: Pull Request Checks

env:
  USE_LOCKFILE: false

on:
  pull_request:
    branches: [ master, alpha, beta ]

jobs:
  pull-request:
    if: "! contains(toJSON(github.event.commits.*.message), '[skip ci]')"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # TOCONFIGURE awaiting https://github.com/actions/setup-node/issues/26 so we can just set this to [lts, latest]
        node-version: [10.x, 14.x]

    steps:

    # region Setup
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Get Yarn Cache Path
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"

    - uses: actions/cache@v2
      id: yarn-cache
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-node-${{ matrix.node }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: ${{ runner.os }}-node-${{ matrix.node }}-yarn-

    - run: "echo Cache Key: ${{ runner.os }}-node-${{ matrix.node }}-yarn-${{ hashFiles('**/yarn.lock') }}"
    - run: "echo Cache Restore-Keys: ${{ runner.os }}-node-${{ matrix.node }}-yarn-"
    - run: "echo Yarn Cache Hit: ${{ steps.yarn-cache.outputs.cache-hit }}"

    - name: Setting Up Node.js (${{ matrix.node-version }})
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    # regionend

    # region Steps
    - run: yarn install --frozen-lockfile
      if: "env.USE_LOCKFILE == 'true'"

    # awaiting --ignore engines is temporary because of "typedoc-plugin-param-names" having engines >=12
    # only this command needs it because I only use no lockfile for libs and only libs need typedoc
    - run: yarn install --no-lockfile --ignore-engines
      if: "env.USE_LOCKFILE == 'false'"

    - name: Commits to Lint
      run: git log ${{github.event.pull_request.base.sha}}..${{github.event.pull_request.head.sha}} --graph --abbrev-commit --decorate --format=format:'%h%d%n%s (%cr) - %an (%ae)%n%b'

    - name: Lint Commits
      run: yarn commitlint --from ${{github.event.pull_request.base.sha}} --to ${{github.event.pull_request.head.sha}}

    - run: yarn build

    - run: yarn lint:eslint # test command will lint types (coverage runs test script)

    - run: yarn coverage

    - name: Coverage
      uses: romeovs/lcov-reporter-action@v0.2.16
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
    # regionend
