name: Release

env:
  USE_LOCKFILE: false

on:
  push:
    branches: [ master, alpha, beta ]
  repository_dispatch:
    types: [ release ]
    # to trigger: curl -v -H "Accept: application/vnd.github.everest-preview+json" -H "Authorization: token $GH_TOKEN" https://api.github.com/repos/alanscodelog/TOREPONAME/dispatches -d '{ "event_type": "release" }'

jobs:
  release:
    if: "! contains(toJSON(github.event.commits.*.message), '[skip ci]') && ! contains(toJSON(github.event.commits.*.message), '(no-release)')"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        #TOCONFIGURE awaiting https://github.com/actions/setup-node/issues/26 so we can just set this to [lts]
        # ideally we would trigger a release if the build succeeds on both node versions, need to research #future
        node-version: [14.x]

    steps:

    # region Setup
    - uses: actions/checkout@v2

    - name: Setting Up Node.js (${{ matrix.node-version }})
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - uses: pnpm/action-setup@v2.0.1
      name: Install pnpm
      id: pnpm-install
      with:
        version: latest

    - name: Get Pnpm Cache Path
      if: "env.USE_LOCKFILE == 'true'"
      id: pnpm-cache
      run: |
        echo "::set-output name=dir::$(pnpm store path)"

    - uses: actions/cache@v3
      if: "env.USE_LOCKFILE == 'true'"
      name: pnpm cache
      with:
        path: ${{ steps.pnpm-cache.outputs.dir }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - run: "echo Cache Key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}"
    - run: "echo Cache Restore-Keys: ${{ runner.os }}-pnpm-store-"
    - run: "echo Pnpm Cache Hit: ${{ steps.pnpm-cache.outputs.cache-hit }}"
    # regionend

    # region Steps
    - run: pnpm install
      if: "env.USE_LOCKFILE == 'true'"

    - run: pnpm install --no-frozen-lockfile
      if: "env.USE_LOCKFILE == 'false'"

    - run: pnpm build

    - run: pnpm lint:eslint # test command will lint types

    - run: pnpm test

    - name: Release
      # TOCONFIGURE
      if: "env.REMOVE_LINE_TO_ENABLE == 'true'"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: npx semantic-release
    # regionend
