name: Build-Only
# for debugging failing builds (including docs) without releasing or touching master
# does not use cache

env:
  USE_LOCKFILE: false

on:
  push:
    branches: [ build ]
  repository_dispatch:
    types: [ build-only ]
    # to trigger: curl -v -H "Accept: application/vnd.github.everest-preview+json" -H "Authorization: token $GH_TOKEN" https://api.github.com/repos/alanscodelog/TOREPONAME/dispatches -d '{ "event_type": "build-only" }'

jobs:
  build-only:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        #TOCONFIGURE awaiting https://github.com/actions/setup-node/issues/26 so we can just set this to [latest]
        node-version: [14.x, 17.x]

    steps:

    # region Setup
    - uses: actions/checkout@v2

    - name: Setting Up Node.js (${{ matrix.node-version }})
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - uses: pnpm/action-setup@v2.0.1
      name: Install pnpm
      id: pnpm-install
      with:
        version: latest
    # regionend

    # region Steps
    - run: pnpm install
      if: "env.USE_LOCKFILE == 'true'"

    - run: pnpm install --no-frozen-lockfile
      if: "env.USE_LOCKFILE == 'false'"

    - run: pnpm build

    - run: pnpm lint:eslint # test command will lint types

    - run: pnpm test
    # regionend
