name: Build-Only
# for debugging failing builds (including docs) without releasing or touching master
# does not use cache

env:
  USE_LOCKFILE: false

on:
  push:
    branches: [ build ]
  repository_dispatch:
    types: [ build-only ]
    # to trigger: curl -v -H "Accept: application/vnd.github.everest-preview+json" -H "Authorization: token $GH_TOKEN" https://api.github.com/repos/alanscodelog/TOREPONAME/dispatches -d '{ "event_type": "build-only" }'

jobs:
  build-only:
    if: "! contains(toJSON(github.event.commits.*.message), '[skip ci]')"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        #TOCONFIGURE awaiting https://github.com/actions/setup-node/issues/26 so we can just set this to [lts, latest]
        node-version: [10.x, 14.x]

    steps:

    # region Setup
    - uses: actions/checkout@v2

    - name: Setting Up Node.js (${{ matrix.node-version }})
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    # regionend

    # region Steps
    - run: yarn install --frozen-lockfile
      if: "env.USE_LOCKFILE == 'true'"

    # awaiting --ignore engines is temporary because of "typedoc-plugin-param-names" having engines >=12
    # only this command needs it because I only use no lockfile for libs and only libs need typedoc
    - run: yarn install --no-lockfile --ignore-engines
      if: "env.USE_LOCKFILE == 'false'"

    - run: yarn build

    - run: yarn lint:eslint # test command will lint types

    - run: yarn test

    - run: yarn doc
    # regionend
